###Api_1 scenario_1:

POST http://localhost:3000/register
Content-Type:application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

### Api_2 scenario_1:

POST http://localhost:3000/login
Content-Type:application/json


{
  "username": "adam_richard",
  "password": "richard_567"
}

###Api_3 scenario_1:

PUT http://localhost:3000/change-password
Content-Type:application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}